---
title: "Dessication D6 and SPO"
author: "Anna L"
date: "2025-05-29"
output: html_document
---

```{r}
library(tidyr)
library(ggplot2)
library(stringr)
library(dplyr)
library(tidyverse)
require(survival)
require(extrafont)


theme_set(theme_classic() +
  theme(axis.title = element_text(size = 16),
        axis.title.x = element_text(margin = margin(t = 15, b = 15)),
        axis.title.y = element_text(margin = margin(l = 15, r = 15)),
        axis.text = element_text(size = 13),
        axis.text.x = element_text(margin = margin(t = 5)),
        axis.text.y = element_text(margin = margin(r = 5)),
        #axis.line.x = element_line(linewidth = 1),
        #axis.line.y = element_line(linewidth = 1),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_line(linewidth = 1),
        axis.ticks.y = element_line(linewidth = 1),
        axis.ticks.length = unit(.1, "in"),
        panel.border = element_rect(color = "grey20", fill = NA, linewidth = 1.5),
        legend.text = element_text(size = 14),
        strip.text = element_text(size = 14),
        strip.background = element_blank()
        ))
```

```{r}
setwd("C:/Users/ajl21/Indiana University/Lennon, Jay - DoL/Anna/Dessication_assay/Survivorship")
#data: Turbidity 0 alive 1 death; Strain 1 Delta 6 0 SPOIIE; 
#Experiment 5- desiccation 24 hr; Experiment 6 - desiccation 48 hr; desiccation 7 - 4 hours 
data <- read.csv("20250529_1418_DA_D6SPO.csv")# 1 is D6 and 2 is SPO; Event - 0 if lived 1 if died
data
data$Strain <- factor(data$Strain) 
surv <-data


```

```{r}
biofsurv <- Surv(surv$Day,surv$Event)
print(biofsurv)
biofsurv.fit <- survfit(biofsurv ~ surv$Strain, conf.int = TRUE, 
                type = "kaplan-meier")
biofsurv.diff <- survdiff(Surv(surv$Hour,surv$Event) ~ surv$Strain, data = surv)
```

```{r}
# Convert numeric Strain to a factor with meaningful labels
surv$Strain <- factor(surv$Strain, levels = c(1, 2), labels = c("Delta6", "SPOIIE"))

# Create survival object
biofsurv <- Surv(surv$Day, surv$Event)

# Fit Kaplan-Meier model
biofsurv.fit <- survfit(biofsurv ~ Strain, data = surv)

# Define colors for each strain
strain_levels <- levels(surv$Strain)  # "WT", "Mutant"
strain_colors <- setNames(c("blue", "red"), strain_levels)

# Extract group labels from strata
strata_names <- names(biofsurv.fit$strata)  # e.g., "Strain=WT", "Strain=Mutant"
strain_labels <- sub("Strain=", "", strata_names)

# Plot survival curves
plot(biofsurv.fit,
     col = strain_colors[strain_labels],
     lty = 1,
     conf.int = TRUE,
     mark.time = FALSE,
     xlab = "Time (day)", ylab = "Survival Probability",
     main = "Survivorship Over Time",
     xlim = c(0, 5), ylim = c(0, 1),
     cex.lab = 1.5, cex.axis = 1.2, las = 1, lwd = 2,
     yaxt = "n", xaxt = "n")

# Add axes and box
axis(1, at = seq(0, 5, by = 1), cex.axis = 1.2)
axis(2, at = seq(0, 1, by = 0.2), las = 1, cex.axis = 1.2)
box(lwd = 2)

# Add legend
legend("topright", legend = strain_levels,
       col = strain_colors, lty = 1, lwd = 2)


```

```{r}
plate.aov <- aov(Event ~ Strain, data = data)
summary(plate.aov)


```