---
title: "replicate"
author: "Anna L"
date: "2025-05-23"
output: html_document
---

```{r}
require(survival)
require(extrafont)
setwd("C:/Users/ajl21/Indiana University/Lennon, Jay - DoL/Anna/Dessication_assay/Survivorship")
surv <- read.table("./Biofilm_Survivorship.txt",header=TRUE,sep="\t")
biofsurv <- Surv(surv$Days,surv$Event)
biofsurv
biofsurv.fit <- survfit(biofsurv ~ surv$Group, conf.int = TRUE, 
                type = "kaplan-meier")
biofsurv.diff <- survdiff(Surv(surv$Days,surv$Event) ~ surv$Group, data = surv)
```

Plotting
```{r}

par(mar = c(5, 7, 5, 7))
plot(biofsurv.fit, conf.int = TRUE, mark.time = FALSE,
  xlim = c(0,50), ylim = c(0,1),
  lty = c(1,3,3,1,3,3),
  col = c("black", "grey", "grey", "black", "grey", "grey"),
  xlab = "Time (d)",
  ylab = "", cex.lab = 1.5, cex.axis = 1.2, las = 1, lwd = 2,
  yaxt = "n", xaxt = "n")
  box(lwd=2)

mtext("Survivorship", side = 2, outer = TRUE, cex = 1.5, line = -3, adj = 0.5)

axis(side = 2, labels = T, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
       at = c(0, 0.25, 0.5, 0.75, 1.0))
axis(side = 4, labels = F, lwd.ticks = 2, 
       at = c(0, 0.25, 0.5, 0.75, 1.0))
axis(side = 1, labels = T, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
       at = c(0, 10, 20, 30, 40, 50))
axis(side = 3, labels = F, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
       at = c(0, 10, 20, 30, 40, 50))

text(44, 0.65, "OE", cex = 1.25)
text(25, 0.41, "NM", cex = 1.25)
```