---
title: "Dessication D6 and SPO"
author: "Anna L"
date: "2026-21-1"
output: html_document
---

```{r}
library(tidyr)
library(ggplot2)
library(stringr)
library(dplyr)
library(tidyverse)

theme_set(theme_classic() +
  theme(axis.title = element_text(size = 16),
        axis.title.x = element_text(margin = margin(t = 15, b = 15)),
        axis.title.y = element_text(margin = margin(l = 15, r = 15)),
        axis.text = element_text(size = 13),
        axis.text.x = element_text(margin = margin(t = 5)),
        axis.text.y = element_text(margin = margin(r = 5)),
        #axis.line.x = element_line(linewidth = 1),
        #axis.line.y = element_line(linewidth = 1),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_line(linewidth = 1),
        axis.ticks.y = element_line(linewidth = 1),
        axis.ticks.length = unit(.1, "in"),
        panel.border = element_rect(color = "grey20", fill = NA, linewidth = 1.5),
        legend.text = element_text(size = 14),
        strip.text = element_text(size = 14),
        strip.background = element_blank()
        ))
```

```{r}
setwd("C:/Users/ajl21/github/division.labor/System_validation/")

blank <-read.csv("20260116_system_validation_blank.csv")

wt <- read.csv("20260120_1430_sv_wt.csv")
co<-read.csv("20260120_1430_sv_coexist.csv")

alaE <- read.csv("20260120_1430_sv_alaE.csv")
pheE <- read.csv("20260120_1430_sv_pheE.csv")
serE <- read.csv("20260120_1430_sv_serE.csv")
tyrE <- read.csv("20260120_1430_sv_tyrE.csv")

alaK <- read.csv("20260120_1430_sv_alaK.csv")
pheK <- read.csv("20260120_1430_sv_pheK.csv")
serK <- read.csv("20260120_1430_sv_serK.csv")
tyrK <- read.csv("20260120_1430_sv_tyrK.csv")

#f.convert <- function(df) {
#  df[-1] <- lapply(df[-1], function(x) as.numeric(as.character(x)))
#  df}

```

```{r}
SAT <- mean(blank$X1)
SA<- mean(blank$X2)
SPT <- mean(blank$X3)
SP <- mean(blank$X4)
SST <- mean(blank$X5)
SS <- mean(blank$X6)
STT <- mean(blank$X7)
ST <- mean(blank$X8)
SMT <- mean(blank$X9)
SM <- mean(blank$X10)

#SAT

```

```{r}
#subtracting blank values 

alaE <- rbind(
  alaE[1:2,2:12] - SAT,
  alaE[3:4, 2:12] - SA,
  alaE[5:6, 2:12] - SMT,
  alaE[7:8, 2:12] - SM
)


alaK <- rbind(
  alaK[1:2,2:12] - SAT,
  alaK[3:4, 2:12] - SA,
  alaK[5:6, 2:12] - SMT,
  alaK[7:8, 2:12] - SM
)


pheE <- rbind(
  pheE[1:2,2:12] - SPT,
  pheE[3:4, 2:12] - SP,
  pheE[5:6, 2:12] - SMT,
  pheE[7:8, 2:12] - SM
)



pheK <- rbind(
  pheK[1:2,2:12] - SPT,
  pheK[3:4, 2:12] - SP,
  pheK[5:6, 2:12] - SMT,
  pheK[7:8, 2:12] - SM
)


serE <- rbind(
  serE[1:2,2:12] - SST,
  serE[3:4, 2:12] - SS,
  serE[5:6, 2:12] - SMT,
  serE[7:8, 2:12] - SM
)


serK <- rbind(
  serK[1:2,2:12] - SST,
  serK[3:4, 2:12] - SS,
  serK[5:6, 2:12] - SMT,
  serK[7:8, 2:12] - SM
)



tyrE <- rbind(
  tyrE[1:2,2:12] - SST,
  tyrE[3:4, 2:12] - SS,
  tyrE[5:6, 2:12] - SMT,
  tyrE[7:8, 2:12] - SM
)


tyrK <- rbind(
  tyrK[1:2,2:12] - SST,
  tyrK[3:4, 2:12] - SS,
  tyrK[5:6, 2:12] - SMT,
  tyrK[7:8, 2:12] - SM
)


wt <-rbind(wt[1:4,2:12]-SMT,
           wt[5:8,2:12]-SM)

co <-rbind(co[2:8, 2:12]-SMT)
```

```{r}

```